name: Vite React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build project
      - name: Build project
        run: npm run build

      # 5️⃣ Deploy to server via SSH
      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.4.188.251.116 }}
          username: ${{ secrets.azureuser }}
          key: ${{ secrets.git@github.com:Chandini-lv/food-business-demo.git }}
          source: "dist/*"
          target: ${{ secrets.var/www/food-business-demo }}

      # 6️⃣ Restart NGINX (optional but recommended)
      - name: Restart NGINX
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.4.188.251.116 }}
          username: ${{ secrets.azureuser }}
          key: ${{ secrets.git@github.com:Chandini-lv/food-business-demo.git }}
          script: |
            sudo systemctl restart nginx
