name: React Build Check

on:
  push:
    branches:
      - development
      - testing
      - production

  pull_request:
    branches:
      - main
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build
