name: Production Deployment

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Restart Production App
        run: |
          pm2 restart production-app || pm2 start npm --name "production-app" -- start
